/*
 * This source file was generated by the Gradle 'init' task
 */
package miniproject;

import org.junit.jupiter.api.Test;

import miniproject.app.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
